<?php
/**
 * The kses tag pass as the reference runs it: what wp_kses_post keeps of text,
 * pseudo-tags, comments and bogus comments, closing tags, malformed and
 * duplicate attributes, attribute-name junk, and block delimiters (whose
 * attribute values kses filters and writes back); wp_kses_split on its own;
 * wp_pre_kses_less_than; wp_pre_kses_block_attributes; the JSON
 * serialize_block_attributes writes. Same protocol as api-probe.php.
 */

$log = [];
$say = static function (string $label, $value) use (&$log): void {
    $log[] = [$label, $value];
};
$post = [
    'Five < six & seven',
    '5 < 6 & 7 > 2',
    'D & <b>',
    'T &amp; &lt;b&gt;',
    'AT&amp;amp;T &amp; friends',
    'A feed for the probe — with an entity.',
    '<p class="lead" style="color:red" id="x" onclick="evil()">Escaped <a href="javascript:alert(1)">js</a> and <a href="relative/page">rel</a></p><style>p{}</style><form><input name="q"></form><object data="x"></object><embed src="y"><meta http-equiv="refresh">',
    '<div><h2>Head</h2><table><tr><td>cell</td></tr></table><video src="v.mp4" controls></video><audio src="a.mp3"></audio><blockquote cite="x">q</blockquote><font color="red">old</font><center>c</center></div>',
    '<p>Summary with <a href="https://example.test/x">a link</a> and <script>alert(1)</script> a script.</p>',
    '<p>Full <strong>content</strong> here.</p><iframe src="https://evil.test/"></iframe><img src="/relative.png" onerror="alert(1)" alt="x">',
    'Ada\'s "quoted" title',
    'Caf&eacute; &nbsp; &copy; &#169; &#xA9; &bogus;',
    '< 6>',
    '<6>',
    '1 <2> 3',
    'a < b > c',
    'a <b> c',
    'x <- y',
    '<-->',
    '< >',
    '<>',
    'a<b',
    'if a<b and c>d',
    'a < b',
    '< b',
    '<  /b>',
    '< /b >',
    '<-x>',
    '<x->',
    '< x-y z="1">t</ x-y>',
    '<a-b>t</a-b>',
    '<	b>t</b>',
    '<
b>t</b>',
    '<b >x</b >',
    '< b>x< /b>',
    '<1a>',
    '<a1>x</a1>',
    '<!-- c -->',
    '<!x>',
    '<?php x ?>',
    '< !-- c -->',
    '<3',
    'I <3 you >',
    '<<b>>',
    '<b<i>>x',
    '>',
    'a > b',
    '<a href="x">y<',
    '< p',
    '<p',
    '< p>t',
    '<p class="x"',
    '<p class="x" title="y>z">t</p>',
    '<p title=\'a>b\'>t</p>',
    '<p title=a>b>t</p>',
    '</ b>',
    '</ x>',
    '</ 1>',
    '</ a href=\'javascript:x\'>',
    '</>',
    '</ >',
    '</b x=\'1\'>',
    '</b class=x>',
    '</B>',
    '<B>x</B>',
    '<B CLASS="y">x</B>',
    '</ b x="<">',
    '<!DOCTYPE html>',
    '<!x y=\'>\'>',
    '<!-->',
    '<!--x',
    '<!---->',
    '<! x>',
    '<!>',
    '<![CDATA[x]]>',
    '<!--a-->b-->',
    '<!-- a <b> -->',
    '<!--<script>-->',
    '<!x
onload=alert(1)>',
    '<p title=\'x\'',
    '<p a=1&b',
    '<p a="&amp;"',
    'x <p
class=y',
    'a < b <c>',
    'a < b\'s',
    '<a href="x',
    '<a href=\'x',
    '<p class="x" =foo>t',
    '<p class="x" "junk">t',
    '<p class="x" title=>t',
    '<p class=x" id="y">t',
    '<p class="x"title="y">t',
    '<p class="x" title="y" class="z">t',
    '<p CLASS="x">t',
    '<p class = "x">t',
    '<p class=\'x\' id="y" hidden>t',
    '<p title="a"b">t',
    '<p title=a"b>t',
    '<p title=`x`>t',
    '<p/class="x">t',
    '<p class="x"/>',
    '<br/>',
    '<br />',
    '<br/ >',
    '<img src="x"/>',
    '<p data-x="1" aria-label="y">t',
    '<p data-="1">t',
    '<p onclick=x class=y>t',
    '<p class="a&b">t',
    '<p class="a\'b">t',
    '<p class=\'a"b\'>t',
    '<p class>t',
    '<p class="">t',
    '<p   class="x"   >t',
    '<p	class="x"
>t',
    '<p class="x" / >t',
    '<p class="x"// >t',
    '<hr noshade>',
    '<hr noshade="noshade">',
    '<p hidden>t</p>',
    '<p id=1 id=2>t',
    '<p class="x" class>t',
    '<p title="x" title=\'y\'>t',
    '<!a>',
    '<!xyz>',
    '<!X>',
    '<!1>',
    '<!-x>',
    '<!x y>',
    '<!doctype html>',
    '<!DOCTYPEx>',
    '<!xDOCTYPE>',
    '<!x-->',
    '<!--x--!>',
    '<!- x>',
    '<!--->',
    '<!--a->',
    '<!-- a -- b -->',
    '<!--a&b-->',
    '<!--a"b-->',
    '<!-- <!-- -->',
    '<!--a--><!--b-->',
    '</1>',
    '</%>',
    '</%x y>',
    '</-x>',
    '</	b>',
    '</
b>',
    '</b >',
    '</ b >',
    '</b/>',
    '</b/ >',
    '</b\'>',
    '</b">',
    '</x-y>',
    '</ X>',
    '</ b class="y">',
    '</ !>',
    '</=>',
    '</ &amp;>',
    '</ a&b>',
    '</ "q">',
    '<p class="x" title=\'y>t',
    '<p class="x" =>t',
    '<p class="x" ="y">t',
    '<p =x class="y">t',
    '<p "a" class="y">t',
    '<p class="x" ti"tle="y">t',
    '<p class="x" title= >t',
    '<p class="x" a=b=c>t',
    '<p class="x" a="b"="c">t',
    '<p class="x" @click="y">t',
    '<p class="x" :prop="y">t',
    '<p class="x" a:b="y">t',
    '<p class="x" _a="y">t',
    '<p class="x" 1a="y">t',
    '<p class="x" -a="y">t',
    '<p class="x" title="y"z>t',
    '<p class="x" title="y"z="w">t',
    '<p class="x" \'junk\'>t',
    '<p class="x" \'ju nk\' id="z">t',
    '<p class="x" "ju nk" id="z">t',
    '<p class="x" title=">t',
    '<p class="x" title=\'>t',
    '<p title="x" class="a"b c">t',
    '<p class=\'x\' title=\'y\' z>t',
    '<p class="x" =   >t',
    '<p class=   "x">t',
    '<p class=\'\'>t',
    '<p class=>t',
    '<p class= id="y">t',
    '<P>x</p>',
    '<bR>',
    '<IMG SRC="x" ALT="y">',
    '<a HREF="https://x.test/">l</A>',
    '<p data-X="1">t',
    '<p ARIA-Label="y">t',
    '<div DATA-a="1">t</div>',
    '<BUTTON TYPE="button">b</BUTTON>',
    '<!-- wp:group {"style":{"color":{"background":"var(--wp--preset--color--x)"}}} --><div class="wp-block-group">x</div><!-- /wp:group -->',
    '<!-- wp:paragraph --><p>a -- b</p><!-- /wp:paragraph -->',
    '<!-- not a block -- really -->',
    '<!-- wp:core/html {"a":"<b>"} --><b>x</b><!-- /wp:core/html -->',
    '<!-- wp:paragraph {"x":"a--b"} /-->',
    '<!-- wp:paragraph-->x<!-- /wp:paragraph-->',
    '<p data-a_b="1">t',
    '<p data-a.b="1">t',
    '<p data-a:b="1">t',
    '<p data-1="1">t',
    '<p data--="1">t',
    '<p aria-="1">t',
    '<p aria-x_y="1">t',
    '<p @class="evil">t',
    '<p -id="x">t',
    '<p 1title="x">t',
    '<p .title="x">t',
    '<p ti.tle="x">t',
    '<p #id="x">t',
    '<p $class="x">t',
    '<p !title="x">t',
    '<p é="x" title="y">t',
    '<!-- hi --->',
    '<!-- hi ---->',
    'x <!-- wp:a/b {"a":"x"} ---> y',
];
$split = [
    'a < b\'s',
    '<b',
    'x <p title="q"',
    '<b>ok</b> < c',
    '<!-- c -->',
];
$blocks = [
    '<!-- wp:paragraph {"content":"<script>alert(1)</script><b>x</b>"} --><p>x</p><!-- /wp:paragraph -->',
    '<!-- wp:group {"a":"<i onclick=\\"x\\">i</i>"} --><div><!-- wp:paragraph {"b":"<img src=x onerror=y>"} --><p>y</p><!-- /wp:paragraph --></div><!-- /wp:group -->',
    '<!-- wp:x/y {"a":1,"b":true,"c":null,"d":[1,"x",2.5],"e":{"f":"g"},"h":"é/ü \' \\" & < > \\\\ \\n"} /-->',
    '<!-- wp:x/y {"<b>k</b>":"v","on<i>x":"w"} /-->',
    'before <!-- wp:x/y {"a":"--"} /--> middle <p>z</p> after',
    '<!-- wp:x/y {bad} --><p>q</p><!-- /wp:x/y -->',
    '<!-- wp:core/paragraph {"a":"b"} --><p>c</p><!-- /wp:core/paragraph -->',
    '<!-- wp:paragraph   --><p>s</p><!-- /wp:paragraph   -->',
    '<!-- wp:paragraph {"a":"b"}--><p>s</p><!-- /wp:paragraph -->',
    '<p>plain</p><!-- hi -->',
    '<!-- wp:x/y {"a":"b"} --->x<!-- /wp:x/y --->',
    '<!-- wp:x/y {"url":"javascript:alert(1)","href":"https://ok.test/"} /-->',
    '<!-- wp:x/y {"a":"1.0","b":1.0,"c":-0,"d":1e3,"e":"","f":[],"g":{}} /-->',
    '<!-- wp:x/y {"a":"<b>","b":"--"} /-->',
    '<!-- wp:x/y {"a":"x"} -->unclosed',
    '<!-- /wp:x/y -->stray closer',
];
$lessThan = [
    'a < b\'s "q" &amp; & &bogus; &#39; &eacute; <c>',
    'x <y',
    '<<',
    'a <
 b',
    'a < b > c',
    '<a href="x">',
    '3 < 4 &lt; 5',
    '<p title=\'x\'',
    'é < ü',
    'bad �( < x',
    '< &#x27; &#0000039; &#x00;',
];

foreach (array_chunk($post, 40) as $i => $chunk) {
    $say("wp_kses_post " . ($i + 1), array_map(static fn (string $html): array => [$html, wp_kses_post($html)], $chunk));
}
$say("wp_kses_split", array_map(static fn (string $html): array => [$html, wp_kses_split($html, "post", wp_allowed_protocols())], $split));
$say("wp_pre_kses_less_than", array_map(static fn (string $html): array => [$html, wp_pre_kses_less_than($html)], $lessThan));
$say("wp_pre_kses_block_attributes", array_map(static fn (string $html): array => [$html, wp_pre_kses_block_attributes($html, "post", wp_allowed_protocols()), wp_kses_post($html)], $blocks));
$say("serialize_block_attributes", serialize_block_attributes(["h" => "é/ü ' \" & < > \\\\ \n", "n" => 1.0, "f" => 2.5, "e" => [], "z" => -0.0, "u" => "\u{2028}\u{1F600}", "c" => "\x01", "--" => "a--b"]));
$say("pre_kses defaults", array_keys(array_merge(...array_values($GLOBALS["wp_filter"]["pre_kses"]->callbacks ?? [[]]))));

echo json_encode($log, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE), "\n";
