<?php
/**
 * Writes inert placeholders for reference symbols the facade lacks, from the
 * inventory's signatures: functions into wp-api/placeholders.php, classes
 * into wp-api/classes/placeholders/. A placeholder returns the neutral value
 * of its documented type and does nothing else; it exists so a plugin that
 * references the symbol loads instead of being skipped.
 *
 *   php tests/tools/stub-symbols.php <names.json>   (a {"functions": [], "classes": []} file, e.g. from runtime-report)
 */

$root = dirname(__DIR__, 2);
$names = json_decode((string) file_get_contents($argv[1] ?? 'php://stdin'), true) ?: [];
$functions = json_decode((string) file_get_contents($root . '/contracts/api/functions.json'), true);
$classes = json_decode((string) file_get_contents($root . '/contracts/api/classes.json'), true);

$declared = ['functions' => [], 'classes' => []];
$declaredParents = [];
$declaredMethods = [];
foreach (array_merge(glob($root . '/public/minn/wp-api/*.php'), glob($root . '/public/minn/wp-api/classes/*.php'), glob($root . '/public/minn/wp-api/simplepie/*.php'), glob($root . '/public/minn/wp-api/requests/*.php')) as $file) {
    if (basename($file) === 'placeholders.php') {
        continue;
    }
    $src = (string) file_get_contents($file);
    preg_match_all('/^function\s+(\w+)\s*\(/m', $src, $m);
    $declared['functions'] += array_fill_keys(array_map('strtolower', $m[1]), true);
    preg_match_all('/^(?:abstract\s+|final\s+)?(?:class|interface|trait)\s+(\w+)(?:\s+extends\s+(\w+))?/m', $src, $m, PREG_SET_ORDER);
    foreach ($m as $found) {
        $declared['classes'][strtolower($found[1])] = true;
        if (isset($found[2])) {
            $declaredParents[strtolower($found[1])] = strtolower($found[2]);
        }
        // The methods a hand-written class declares, so a placeholder child inherits rather than redeclares them.
        // An abstract method is not inherited: the placeholder must give it a body.
        if (preg_match('/^(?:abstract\s+|final\s+)?(?:class|interface|trait)\s+' . $found[1] . '\b(.*?)^}/ms', $src, $bodyMatch)) {
            preg_match_all('/^([^\n]*)\bfunction\s+(\w+)\s*\(/m', $bodyMatch[1], $fm, PREG_SET_ORDER);
            $concrete = array_filter($fm, static fn (array $line): bool => !str_contains($line[1], 'abstract'));
            $declaredMethods[strtolower($found[1])] = array_fill_keys(array_map(static fn (array $line): string => strtolower($line[2]), $concrete), true);
        }
    }
}
$inheritedMethods = static function (string $class) use (&$inheritedMethods, &$declaredParents, &$declaredMethods, $classes): array {
    $methods = [];
    $parent = $classes[$class]['extends'] ?? null;
    while ($parent !== null) {
        $lower = strtolower($parent);
        if (isset($declaredMethods[$lower])) {
            $methods += $declaredMethods[$lower];
            $parent = isset($declaredParents[$lower]) ? $declaredParents[$lower] : null;
        } else {
            $parent = $classes[$parent]['extends'] ?? null;
        }
    }
    return $methods;
};

$literal = static function ($value) use (&$literal): string {
    if (is_array($value) && isset($value['const']) && count($value) === 1) {
        return (string) $value['const'];
    }
    if (is_array($value)) {
        $items = [];
        $list = array_is_list($value);
        foreach ($value as $k => $v) {
            $items[] = ($list ? '' : var_export($k, true) . ' => ') . $literal($v);
        }
        return '[' . implode(', ', $items) . ']';
    }
    return var_export($value, true);
};
$params = static function (array $list) use ($literal): string {
    $out = [];
    foreach ($list as $p) {
        $out[] = (!empty($p['byRef']) ? '&' : '') . (!empty($p['variadic']) ? '...' : '') . '$' . $p['name'] . (array_key_exists('default', $p) ? ' = ' . $literal($p['default']) : '');
    }
    return implode(', ', $out);
};
$body = static function (?string $returns, string $name): string {
    $type = ltrim((string) $returns, '?');
    if ($returns === 'void' || str_starts_with($name, 'the_') || str_starts_with($name, 'do_') || str_starts_with($name, 'print_') || str_starts_with($name, 'display')) {
        return '';
    }
    if (str_starts_with((string) $returns, '?')) {
        return 'return null;';
    }
    return match ($type) {
        'array' => 'return [];',
        'bool' => 'return false;',
        'string' => 'return \'\';',
        'int', 'float' => 'return 0;',
        default => 'return null;',
    };
};

$fnOut = "<?php\n// Generated by tests/tools/stub-symbols.php from the inventory: inert placeholders for symbols plugins reference but the engine does not implement. Do not edit; regenerate.\n";
$written = ['functions' => 0, 'classes' => 0];
foreach ($names['functions'] ?? [] as $name) {
    if (isset($declared['functions'][strtolower($name)]) || !isset($functions[$name])) {
        continue;
    }
    $spec = $functions[$name];
    $b = $body($spec['returns'] ?? null, $name);
    $fnOut .= "\nfunction {$name}(" . $params($spec['params'] ?? []) . ")\n{\n    \\Minn\\Runtime\\PlaceholderTrace::hit('{$name}');\n" . ($b === '' ? '' : "    {$b}\n") . "}\n";
    $written['functions']++;
}
file_put_contents($root . '/public/minn/wp-api/placeholders.php', $fnOut);

// Classes go into one file in dependency order: a placeholder's parent or
// interface that the facade lacks becomes a placeholder too.
$wanted = [];
$queue = array_values($names['classes'] ?? []);
while ($queue !== []) {
    $name = array_shift($queue);
    if (isset($wanted[$name]) || isset($declared['classes'][strtolower($name)]) || !isset($classes[$name]) || str_contains($name, '\\')) {
        continue;
    }
    $wanted[$name] = true;
    foreach (array_merge((array) ($classes[$name]['extends'] ?? []), (array) ($classes[$name]['implements'] ?? [])) as $dep) {
        if (!isset($declared['classes'][strtolower($dep)]) && !class_exists($dep, false) && !interface_exists($dep, false) && isset($classes[$dep])) {
            $queue[] = $dep;
        }
    }
}
$ordered = [];
$place = static function (string $name) use (&$place, &$ordered, $classes, $wanted, $declared): void {
    if (isset($ordered[$name]) || !isset($wanted[$name])) {
        return;
    }
    foreach (array_merge((array) ($classes[$name]['extends'] ?? []), (array) ($classes[$name]['implements'] ?? [])) as $dep) {
        $place($dep);
    }
    $ordered[$name] = true;
};
foreach (array_keys($wanted) as $name) {
    $place($name);
}
$classOut = "<?php\n// Generated by tests/tools/stub-symbols.php from the inventory: inert placeholder classes so plugins that reference them load. Parents come first. Do not edit; regenerate.\n";
// The classes the reference lets plugins hang properties on (captured by reflection).
$dynamic = array_flip(json_decode((string) file_get_contents($root . '/public/minn/data/dynamic-properties.json'), true)['classes'] ?? []);
foreach (array_keys($ordered) as $name) {
    $spec = $classes[$name];
    $kind = $spec['kind'] ?? 'class';
    $keyword = $kind === 'interface' ? 'interface' : ($kind === 'trait' ? 'trait' : (($kind === 'abstract' ? 'abstract ' : '') . 'class'));
    $out = "\n" . (isset($dynamic[$name]) ? "#[AllowDynamicProperties]\n" : '') . "{$keyword} {$name}";
    if (!empty($spec['extends'])) {
        $out .= ' extends ' . $spec['extends'];
    }
    if (!empty($spec['implements'])) {
        $out .= ' implements ' . implode(', ', (array) $spec['implements']);
    }
    $out .= "\n{\n";
    foreach ($spec['constants'] ?? [] as $const => $value) {
        $out .= "    const {$const} = " . $literal(is_array($value) && array_key_exists('value', $value) ? $value['value'] : $value) . ";\n";
    }
    foreach ($spec['properties'] ?? [] as $prop => $p) {
        $out .= '    ' . ($p['visibility'] ?? 'public') . (!empty($p['static']) ? ' static' : '') . ' $' . $prop . (array_key_exists('default', $p) ? ' = ' . $literal($p['default']) : '') . ";\n";
    }
    $inherited = $inheritedMethods($name);
    foreach ($spec['methods'] ?? [] as $method => $m) {
        if (isset($inherited[strtolower($method)])) {
            continue;
        }
        $b = $kind === 'interface' ? null : $body($m['returns'] ?? null, $method);
        $out .= "\n    " . ($m['visibility'] ?? 'public') . (!empty($m['static']) ? ' static' : '') . " function {$method}(" . $params($m['params'] ?? []) . ')' . ($b === null ? ";\n" : "\n    {\n        \\Minn\\Runtime\\PlaceholderTrace::hit('{$name}::{$method}');\n" . ($b === '' ? '' : "        {$b}\n") . "    }\n");
    }
    $classOut .= $out . "}\n";
    $written['classes']++;
}
@mkdir($root . '/public/minn/wp-api/classes/placeholders');
file_put_contents($root . '/public/minn/wp-api/classes/placeholders/Placeholders.php', $classOut);
echo json_encode($written), "\n";
