<?php
// Generated by tests/tools/stub-symbols.php from the inventory: inert placeholder classes so plugins that reference them load. Parents come first. Do not edit; regenerate.

#[AllowDynamicProperties]
class POMO_Reader
{
    public $endian = 'little';
    public $_pos = NULL;
    public $is_overloaded = NULL;

    public function __construct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::__construct');
        return null;
    }

    public function POMO_Reader()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::POMO_Reader');
        return null;
    }

    public function setEndian($endian)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::setEndian');
        return null;
    }

    public function readint32()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::readint32');
        return null;
    }

    public function readint32array($count)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::readint32array');
        return null;
    }

    public function substr($input_string, $start, $length)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::substr');
        return null;
    }

    public function strlen($input_string)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::strlen');
        return null;
    }

    public function str_split($input_string, $chunk_size)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::str_split');
        return null;
    }

    public function pos()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::pos');
        return null;
    }

    public function is_resource()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::is_resource');
        return null;
    }

    public function close()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_Reader::close');
        return null;
    }
}

class POMO_StringReader extends POMO_Reader
{
    public $_str = '';

    public function __construct($str = '')
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_StringReader::__construct');
        return null;
    }

    public function POMO_StringReader($str = '')
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_StringReader::POMO_StringReader');
        return null;
    }

    public function read($bytes)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_StringReader::read');
        return null;
    }

    public function seekto($pos)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_StringReader::seekto');
        return null;
    }

    public function length()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_StringReader::length');
        return null;
    }

    public function read_all()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_StringReader::read_all');
        return null;
    }
}

class POMO_CachedFileReader extends POMO_StringReader
{

    public function __construct($filename)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_CachedFileReader::__construct');
        return null;
    }

    public function POMO_CachedFileReader($filename)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_CachedFileReader::POMO_CachedFileReader');
        return null;
    }
}

class POMO_CachedIntFileReader extends POMO_CachedFileReader
{

    public function __construct($filename)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_CachedIntFileReader::__construct');
        return null;
    }

    public function POMO_CachedIntFileReader($filename)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_CachedIntFileReader::POMO_CachedIntFileReader');
        return null;
    }
}

class POMO_FileReader extends POMO_Reader
{
    public $_f = NULL;

    public function __construct($filename)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_FileReader::__construct');
        return null;
    }

    public function POMO_FileReader($filename)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_FileReader::POMO_FileReader');
        return null;
    }

    public function read($bytes)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_FileReader::read');
        return null;
    }

    public function seekto($pos)
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_FileReader::seekto');
        return null;
    }

    public function is_resource()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_FileReader::is_resource');
        return null;
    }

    public function feof()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_FileReader::feof');
        return null;
    }

    public function close()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_FileReader::close');
        return null;
    }

    public function read_all()
    {
        \Minn\Runtime\PlaceholderTrace::hit('POMO_FileReader::read_all');
        return null;
    }
}

class WP_Font_Face_Resolver
{

    public static function get_fonts_from_theme_json()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Font_Face_Resolver::get_fonts_from_theme_json');
        return null;
    }

    public static function get_fonts_from_style_variations()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Font_Face_Resolver::get_fonts_from_style_variations');
        return null;
    }

    private static function parse_settings($settings)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Font_Face_Resolver::parse_settings');
        return null;
    }

    private static function maybe_parse_name_from_comma_separated_list($font_family)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Font_Face_Resolver::maybe_parse_name_from_comma_separated_list');
        return null;
    }

    private static function convert_font_face_properties($font_face_definition, $font_family_property)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Font_Face_Resolver::convert_font_face_properties');
        return null;
    }

    private static function to_theme_file_uri($src)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Font_Face_Resolver::to_theme_file_uri');
        return null;
    }

    private static function to_kebab_case($data)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Font_Face_Resolver::to_kebab_case');
        return null;
    }
}

class WP_Image_Editor_Imagick extends WP_Image_Editor
{
    protected $image = NULL;
    private $stream_file_data = NULL;
    private $image_given_name = NULL;

    public function __destruct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::__destruct');
        return null;
    }

    public function load()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::load');
        return null;
    }

    public static function set_imagick_time_limit()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::set_imagick_time_limit');
        return null;
    }

    public function resize($max_w, $max_h, $crop = false)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::resize');
        return null;
    }

    protected function thumbnail_image($dst_w, $dst_h, $filter_name = 'FILTER_TRIANGLE', $strip_meta = true)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::thumbnail_image');
        return null;
    }

    public function multi_resize($sizes)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::multi_resize');
        return null;
    }

    public function crop($src_x, $src_y, $src_w, $src_h, $dst_w = NULL, $dst_h = NULL, $src_abs = false)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::crop');
        return null;
    }

    public function rotate($angle)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::rotate');
        return null;
    }

    public function flip($horz, $vert)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::flip');
        return null;
    }

    public function save($destfilename = NULL, $mime_type = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::save');
        return null;
    }

    protected function remove_pdf_alpha_channel()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::remove_pdf_alpha_channel');
        return null;
    }

    protected function _save($image, $filename = NULL, $mime_type = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::_save');
        return null;
    }

    private function write_image($image, $filename)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::write_image');
        return null;
    }

    public function stream($mime_type = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::stream');
        return null;
    }

    protected function strip_meta()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::strip_meta');
        return null;
    }

    protected function pdf_setup()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::pdf_setup');
        return null;
    }

    protected function pdf_load_source()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Image_Editor_Imagick::pdf_load_source');
        return null;
    }
}

class WP_Navigation_Fallback
{

    public static function update_wp_navigation_post_schema($schema)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::update_wp_navigation_post_schema');
        return null;
    }

    public static function get_fallback()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::get_fallback');
        return null;
    }

    private static function get_most_recently_published_navigation()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::get_most_recently_published_navigation');
        return null;
    }

    private static function create_classic_menu_fallback()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::create_classic_menu_fallback');
        return null;
    }

    private static function get_fallback_classic_menu()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::get_fallback_classic_menu');
        return null;
    }

    private static function get_most_recently_created_nav_menu($classic_nav_menus)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::get_most_recently_created_nav_menu');
        return null;
    }

    private static function get_nav_menu_with_primary_slug($classic_nav_menus)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::get_nav_menu_with_primary_slug');
        return null;
    }

    private static function get_nav_menu_at_primary_location()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::get_nav_menu_at_primary_location');
        return null;
    }

    private static function create_default_fallback()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::create_default_fallback');
        return null;
    }

    private static function get_default_fallback_blocks()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Navigation_Fallback::get_default_fallback_blocks');
        return null;
    }
}

class WP_REST_Posts_Controller extends WP_REST_Controller
{
    protected $post_type = NULL;
    protected $meta = NULL;
    protected $password_check_passed = [];
    protected $allow_batch = ['v1' => true];

    public function __construct($post_type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::__construct');
        return null;
    }

    public function check_password_required($required, $post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_password_required');
        return null;
    }

    protected function get_post($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::get_post');
        return null;
    }

    public function can_access_password_content($post, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::can_access_password_content');
        return null;
    }

    protected function prepare_items_query($prepared_args = [], $request = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::prepare_items_query');
        return null;
    }

    protected function prepare_date_response($date_gmt, $date = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::prepare_date_response');
        return null;
    }

    public function check_status($status, $request, $param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_status');
        return null;
    }

    protected function handle_status_param($post_status, $post_type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::handle_status_param');
        return null;
    }

    protected function handle_featured_media($featured_media, $post_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::handle_featured_media');
        return null;
    }

    public function check_template($template, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_template');
        return null;
    }

    public function handle_template($template, $post_id, $validate = false)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::handle_template');
        return null;
    }

    protected function handle_terms($post_id, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::handle_terms');
        return null;
    }

    protected function check_assign_terms_permission($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_assign_terms_permission');
        return null;
    }

    protected function check_is_post_type_allowed($post_type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_is_post_type_allowed');
        return null;
    }

    public function check_read_permission($post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_read_permission');
        return null;
    }

    protected function check_update_permission($post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_update_permission');
        return null;
    }

    protected function check_create_permission($post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_create_permission');
        return null;
    }

    protected function check_delete_permission($post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::check_delete_permission');
        return null;
    }

    public function protected_title_format()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::protected_title_format');
        return null;
    }

    protected function prepare_links($post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::prepare_links');
        return null;
    }

    protected function get_available_actions($post, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::get_available_actions');
        return null;
    }

    protected function get_schema_links()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::get_schema_links');
        return null;
    }

    public function sanitize_post_statuses($statuses, $request, $parameter)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::sanitize_post_statuses');
        return null;
    }

    private function prepare_tax_query($args, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::prepare_tax_query');
        return null;
    }

    private function prepare_taxonomy_limit_schema($query_params)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Posts_Controller::prepare_taxonomy_limit_schema');
        return null;
    }
}

class WP_REST_Attachments_Controller extends WP_REST_Posts_Controller
{
    const IMAGE_SIZE_SOURCE_ORIGINAL = 'source_original';
    const META_KEY_SOURCE_IMAGE = 'source_image';
    const META_KEY_SIDELOAD_FILE_NAME = '_wp_sideloaded_file';
    protected $allow_batch = false;

    protected function prepare_items_query($prepared_args = [], $request = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::prepare_items_query');
        return null;
    }

    protected function create_item_from_url($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::create_item_from_url');
        return null;
    }

    private function remove_client_side_media_processing_filters()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::remove_client_side_media_processing_filters');
    }

    protected function insert_attachment($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::insert_attachment');
        return null;
    }

    protected function handle_featured_media($featured_media, $post_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::handle_featured_media');
        return null;
    }

    public function post_process_item($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::post_process_item');
        return null;
    }

    public function post_process_item_permissions_check($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::post_process_item_permissions_check');
        return null;
    }

    public function edit_media_item_permissions_check($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::edit_media_item_permissions_check');
        return null;
    }

    public function edit_media_item($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::edit_media_item');
        return null;
    }

    protected function prepare_links($post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::prepare_links');
        return null;
    }

    protected function upload_from_data($data, $headers, $time = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::upload_from_data');
        return null;
    }

    public static function get_filename_from_disposition($disposition_header)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::get_filename_from_disposition');
        return null;
    }

    protected function upload_from_file($files, $headers, $time = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::upload_from_file');
        return null;
    }

    protected function get_media_types()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::get_media_types');
        return null;
    }

    protected function check_upload_size($file)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::check_upload_size');
        return null;
    }

    protected function get_edit_media_item_args()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::get_edit_media_item_args');
        return null;
    }

    protected function get_attachment_filename($attachment_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::get_attachment_filename');
        return null;
    }

    protected function get_attachment_filesize($attachment_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::get_attachment_filesize');
        return null;
    }

    public function sideload_item_permissions_check($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::sideload_item_permissions_check');
        return null;
    }

    private static function validate_image_size_names($value, $param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::validate_image_size_names');
        return null;
    }

    private static function get_special_image_sizes()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::get_special_image_sizes');
        return [];
    }

    private function validate_image_dimensions($width, $height, $image_size, $attachment_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::validate_image_dimensions');
        return null;
    }

    private function dimension_exceeds_max($value, $max, $tolerance)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::dimension_exceeds_max');
        return false;
    }

    public function sideload_item($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::sideload_item');
        return null;
    }

    private static function filter_wp_unique_filename($filename, $dir, $number, $attachment_filename)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::filter_wp_unique_filename');
        return null;
    }

    protected function validate_sub_size_provenance($attachment_id, $sub_sizes)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::validate_sub_size_provenance');
        return null;
    }

    protected function get_sideloaded_file_names($attachment_id, $include_provenance = true)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::get_sideloaded_file_names');
        return [];
    }

    protected function get_attachment_upload_subdir($attached_file)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::get_attachment_upload_subdir');
        return null;
    }

    public function finalize_item($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Attachments_Controller::finalize_item');
        return null;
    }
}

class WP_REST_Revisions_Controller extends WP_REST_Controller
{
    private $parent_post_type = NULL;
    protected $meta = NULL;
    private $parent_controller = NULL;
    private $parent_base = NULL;

    public function __construct($parent_post_type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Revisions_Controller::__construct');
        return null;
    }

    protected function get_parent($parent_post_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Revisions_Controller::get_parent');
        return null;
    }

    protected function get_revision($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Revisions_Controller::get_revision');
        return null;
    }

    protected function prepare_items_query($prepared_args = [], $request = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Revisions_Controller::prepare_items_query');
        return null;
    }

    private function restore_post_data($previous_post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Revisions_Controller::restore_post_data');
    }

    protected function prepare_date_response($date_gmt, $date = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Revisions_Controller::prepare_date_response');
        return null;
    }

    protected function prepare_excerpt_response($excerpt, $post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Revisions_Controller::prepare_excerpt_response');
        return null;
    }
}

class WP_REST_Autosaves_Controller extends WP_REST_Revisions_Controller
{
    private $parent_post_type = NULL;
    private $parent_controller = NULL;
    private $revisions_controller = NULL;
    private $parent_base = NULL;

    public function __construct($parent_post_type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Autosaves_Controller::__construct');
        return null;
    }

    protected function get_parent($parent_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Autosaves_Controller::get_parent');
        return null;
    }

    public function create_post_autosave($post_data, $meta = [])
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Autosaves_Controller::create_post_autosave');
        return null;
    }
}

class WP_REST_Block_Patterns_Controller extends WP_REST_Controller
{
    private $remote_patterns_loaded = NULL;
    protected static $categories_migration = ['buttons' => 'call-to-action', 'columns' => 'text', 'query' => 'posts'];

    public function __construct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Block_Patterns_Controller::__construct');
        return null;
    }

    protected function migrate_pattern_categories($pattern)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Block_Patterns_Controller::migrate_pattern_categories');
        return null;
    }
}

class WP_REST_Blocks_Controller extends WP_REST_Posts_Controller
{

    public function check_read_permission($post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Blocks_Controller::check_read_permission');
        return null;
    }
}

class WP_REST_Comments_Controller extends WP_REST_Controller
{
    protected $meta = NULL;

    public function __construct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::__construct');
        return null;
    }

    protected function get_comment($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::get_comment');
        return null;
    }

    protected function prepare_links($comment)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::prepare_links');
        return null;
    }

    protected function normalize_query_param($query_param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::normalize_query_param');
        return null;
    }

    protected function prepare_status_response($comment_approved)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::prepare_status_response');
        return null;
    }

    protected function handle_status_param($new_status, $comment_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::handle_status_param');
        return null;
    }

    protected function check_read_post_permission($post, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::check_read_post_permission');
        return null;
    }

    protected function check_read_permission($comment, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::check_read_permission');
        return null;
    }

    protected function check_edit_permission($comment)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::check_edit_permission');
        return null;
    }

    public function check_comment_author_email($value, $request, $param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::check_comment_author_email');
        return null;
    }

    protected function check_is_comment_content_allowed($prepared_comment)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::check_is_comment_content_allowed');
        return null;
    }

    private function check_post_type_supports_notes($post_type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Comments_Controller::check_post_type_supports_notes');
        return null;
    }
}

class WP_REST_Menu_Items_Controller extends WP_REST_Posts_Controller
{

    protected function get_nav_menu_item($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menu_Items_Controller::get_nav_menu_item');
        return null;
    }

    protected function check_has_read_only_access($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menu_Items_Controller::check_has_read_only_access');
        return null;
    }

    protected function prepare_links($post)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menu_Items_Controller::prepare_links');
        return null;
    }

    protected function get_schema_links()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menu_Items_Controller::get_schema_links');
        return null;
    }

    protected function prepare_items_query($prepared_args = [], $request = NULL)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menu_Items_Controller::prepare_items_query');
        return null;
    }

    protected function get_menu_id($menu_item_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menu_Items_Controller::get_menu_id');
        return null;
    }
}

class WP_REST_Terms_Controller extends WP_REST_Controller
{
    protected $taxonomy = NULL;
    protected $meta = NULL;
    protected $sort_column = NULL;
    protected $total_terms = NULL;
    protected $allow_batch = ['v1' => true];

    public function __construct($taxonomy)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Terms_Controller::__construct');
        return null;
    }

    public function check_read_terms_permission_for_post($post, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Terms_Controller::check_read_terms_permission_for_post');
        return null;
    }

    protected function get_term($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Terms_Controller::get_term');
        return null;
    }

    protected function prepare_links($term)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Terms_Controller::prepare_links');
        return null;
    }

    protected function check_is_taxonomy_allowed($taxonomy)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Terms_Controller::check_is_taxonomy_allowed');
        return null;
    }
}

class WP_REST_Menus_Controller extends WP_REST_Terms_Controller
{

    protected function get_term($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menus_Controller::get_term');
        return null;
    }

    protected function check_has_read_only_access($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menus_Controller::check_has_read_only_access');
        return null;
    }

    protected function prepare_links($term)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menus_Controller::prepare_links');
        return null;
    }

    protected function get_menu_auto_add($menu_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menus_Controller::get_menu_auto_add');
        return null;
    }

    protected function handle_auto_add($menu_id, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menus_Controller::handle_auto_add');
        return null;
    }

    protected function get_menu_locations($menu_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menus_Controller::get_menu_locations');
        return null;
    }

    protected function handle_locations($menu_id, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Menus_Controller::handle_locations');
        return null;
    }
}

#[AllowDynamicProperties]
abstract class WP_REST_Meta_Fields
{

    protected function get_meta_type()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::get_meta_type');
        return null;
    }

    protected function get_meta_subtype()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::get_meta_subtype');
        return null;
    }

    protected function get_rest_field_type()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::get_rest_field_type');
        return null;
    }

    public function register_field()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::register_field');
        return null;
    }

    public function get_value($object_id, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::get_value');
        return null;
    }

    protected function prepare_value_for_response($value, $request, $args)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::prepare_value_for_response');
        return null;
    }

    public function update_value($meta, $object_id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::update_value');
        return null;
    }

    protected function delete_meta_value($object_id, $meta_key, $name)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::delete_meta_value');
        return null;
    }

    protected function update_multi_meta_value($object_id, $meta_key, $name, $values)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::update_multi_meta_value');
        return null;
    }

    protected function update_meta_value($object_id, $meta_key, $name, $value)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::update_meta_value');
        return null;
    }

    protected function is_meta_value_same_as_stored_value($meta_key, $subtype, $stored_value, $user_value)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::is_meta_value_same_as_stored_value');
        return null;
    }

    protected function get_registered_fields()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::get_registered_fields');
        return null;
    }

    public function get_field_schema()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::get_field_schema');
        return null;
    }

    public static function prepare_value($value, $request, $args)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::prepare_value');
        return null;
    }

    public function check_meta_is_array($value, $request, $param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::check_meta_is_array');
        return null;
    }

    protected function default_additional_properties_to_false($schema)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::default_additional_properties_to_false');
        return null;
    }

    protected static function get_empty_value_for_type($type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Meta_Fields::get_empty_value_for_type');
        return null;
    }
}

class WP_REST_Plugins_Controller extends WP_REST_Controller
{
    const PATTERN = '[^.\\/]+(?:\\/[^.\\/]+)?';

    public function __construct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::__construct');
        return null;
    }

    protected function check_read_permission($plugin)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::check_read_permission');
        return null;
    }

    protected function prepare_links($item)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::prepare_links');
        return null;
    }

    protected function get_plugin_data($plugin)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::get_plugin_data');
        return null;
    }

    protected function get_plugin_status($plugin)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::get_plugin_status');
        return null;
    }

    protected function plugin_status_permission_check($plugin, $new_status, $current_status)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::plugin_status_permission_check');
        return null;
    }

    protected function handle_plugin_status($plugin, $new_status, $current_status)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::handle_plugin_status');
        return null;
    }

    public function validate_plugin_param($file)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::validate_plugin_param');
        return null;
    }

    public function sanitize_plugin_param($file)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::sanitize_plugin_param');
        return null;
    }

    protected function does_plugin_match_request($request, $item)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::does_plugin_match_request');
        return null;
    }

    protected function is_plugin_installed($plugin)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::is_plugin_installed');
        return null;
    }

    protected function is_filesystem_available()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Plugins_Controller::is_filesystem_available');
        return null;
    }
}

class WP_REST_Post_Meta_Fields extends WP_REST_Meta_Fields
{
    protected $post_type = NULL;

    public function __construct($post_type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Post_Meta_Fields::__construct');
        return null;
    }

    protected function get_meta_type()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Post_Meta_Fields::get_meta_type');
        return null;
    }

    protected function get_meta_subtype()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Post_Meta_Fields::get_meta_subtype');
        return null;
    }

    public function get_rest_field_type()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Post_Meta_Fields::get_rest_field_type');
        return null;
    }
}

class WP_REST_Settings_Controller extends WP_REST_Controller
{

    public function __construct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Settings_Controller::__construct');
        return null;
    }

    protected function prepare_value($value, $schema)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Settings_Controller::prepare_value');
        return null;
    }

    protected function get_registered_options()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Settings_Controller::get_registered_options');
        return null;
    }

    public function sanitize_callback($value, $request, $param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Settings_Controller::sanitize_callback');
        return null;
    }

    protected function set_additional_properties_to_false($schema)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Settings_Controller::set_additional_properties_to_false');
        return null;
    }
}

class WP_REST_Templates_Controller extends WP_REST_Controller
{
    protected $post_type = NULL;

    public function __construct($post_type)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Templates_Controller::__construct');
        return null;
    }

    public function get_template_fallback($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Templates_Controller::get_template_fallback');
        return null;
    }

    protected function permissions_check($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Templates_Controller::permissions_check');
        return null;
    }

    public function _sanitize_template_id($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Templates_Controller::_sanitize_template_id');
        return null;
    }

    private static function get_wp_templates_original_source_field($template_object)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Templates_Controller::get_wp_templates_original_source_field');
        return null;
    }

    private static function get_wp_templates_author_text_field($template_object)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Templates_Controller::get_wp_templates_author_text_field');
        return null;
    }

    protected function prepare_links($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Templates_Controller::prepare_links');
        return null;
    }

    protected function get_available_actions()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Templates_Controller::get_available_actions');
        return null;
    }
}

class WP_REST_Term_Meta_Fields extends WP_REST_Meta_Fields
{
    protected $taxonomy = NULL;

    public function __construct($taxonomy)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Term_Meta_Fields::__construct');
        return null;
    }

    protected function get_meta_type()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Term_Meta_Fields::get_meta_type');
        return null;
    }

    protected function get_meta_subtype()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Term_Meta_Fields::get_meta_subtype');
        return null;
    }

    public function get_rest_field_type()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Term_Meta_Fields::get_rest_field_type');
        return null;
    }
}

class WP_REST_Themes_Controller extends WP_REST_Controller
{
    const PATTERN = '[^\\/:<>\\*\\?"\\|]+(?:\\/[^\\/:<>\\*\\?"\\|]+)?';

    public function __construct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Themes_Controller::__construct');
        return null;
    }

    public function _sanitize_stylesheet_callback($stylesheet)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Themes_Controller::_sanitize_stylesheet_callback');
        return null;
    }

    protected function check_read_active_theme_permission()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Themes_Controller::check_read_active_theme_permission');
        return null;
    }

    protected function prepare_links($theme)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Themes_Controller::prepare_links');
        return null;
    }

    protected function is_same_theme($theme_a, $theme_b)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Themes_Controller::is_same_theme');
        return null;
    }

    protected function prepare_theme_support($support, $args, $feature, $request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Themes_Controller::prepare_theme_support');
        return null;
    }

    public function sanitize_theme_status($statuses, $request, $parameter)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Themes_Controller::sanitize_theme_status');
        return null;
    }
}

class WP_REST_User_Meta_Fields extends WP_REST_Meta_Fields
{

    protected function get_meta_type()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_User_Meta_Fields::get_meta_type');
        return null;
    }

    protected function get_meta_subtype()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_User_Meta_Fields::get_meta_subtype');
        return null;
    }

    public function get_rest_field_type()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_User_Meta_Fields::get_rest_field_type');
        return null;
    }
}

class WP_REST_Users_Controller extends WP_REST_Controller
{
    protected $meta = NULL;
    protected $allow_batch = ['v1' => true];

    public function __construct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::__construct');
        return null;
    }

    public function check_reassign($value, $request, $param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::check_reassign');
        return null;
    }

    protected function get_user($id)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::get_user');
        return null;
    }

    public function get_current_item($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::get_current_item');
        return null;
    }

    public function update_current_item_permissions_check($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::update_current_item_permissions_check');
        return null;
    }

    public function update_current_item($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::update_current_item');
        return null;
    }

    public function delete_current_item_permissions_check($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::delete_current_item_permissions_check');
        return null;
    }

    public function delete_current_item($request)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::delete_current_item');
        return null;
    }

    protected function prepare_links($user)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::prepare_links');
        return null;
    }

    protected function check_role_update($user_id, $roles)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::check_role_update');
        return null;
    }

    public function check_username($value, $request, $param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::check_username');
        return null;
    }

    public function check_user_password($value, $request, $param)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_REST_Users_Controller::check_user_password');
        return null;
    }
}

#[AllowDynamicProperties]
class WP_Recovery_Mode_Link_Service
{
    const LOGIN_ACTION_ENTER = 'enter_recovery_mode';
    const LOGIN_ACTION_ENTERED = 'entered_recovery_mode';
    private $key_service = NULL;
    private $cookie_service = NULL;

    public function __construct($cookie_service, $key_service)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Recovery_Mode_Link_Service::__construct');
        return null;
    }

    public function generate_url()
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Recovery_Mode_Link_Service::generate_url');
        return null;
    }

    public function handle_begin_link($ttl)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Recovery_Mode_Link_Service::handle_begin_link');
        return null;
    }

    private function get_recovery_mode_begin_url($token, $key)
    {
        \Minn\Runtime\PlaceholderTrace::hit('WP_Recovery_Mode_Link_Service::get_recovery_mode_begin_url');
        return null;
    }
}

class _WP_Editors
{
    public static $mce_locale = NULL;
    private static $mce_settings = [];
    private static $qt_settings = [];
    private static $plugins = [];
    private static $qt_buttons = [];
    private static $ext_plugins = NULL;
    private static $baseurl = NULL;
    private static $first_init = NULL;
    private static $this_tinymce = false;
    private static $this_quicktags = false;
    private static $has_tinymce = false;
    private static $has_quicktags = false;
    private static $has_medialib = false;
    private static $editor_buttons_css = true;
    private static $drag_drop_upload = false;
    private static $translation = NULL;
    private static $tinymce_scripts_printed = false;
    private static $link_dialog_printed = false;

    private function __construct()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::__construct');
        return null;
    }

    public static function parse_settings($editor_id, $settings)
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::parse_settings');
        return null;
    }

    public static function editor($content, $editor_id, $settings = [])
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::editor');
        return null;
    }

    public static function editor_settings($editor_id, $set)
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::editor_settings');
        return null;
    }

    private static function _parse_init($init)
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::_parse_init');
        return null;
    }

    public static function enqueue_scripts($default_scripts = false)
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::enqueue_scripts');
        return null;
    }

    public static function enqueue_default_editor()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::enqueue_default_editor');
        return null;
    }

    public static function print_default_editor_scripts()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::print_default_editor_scripts');
    }

    public static function get_mce_locale()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::get_mce_locale');
        return null;
    }

    public static function get_baseurl()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::get_baseurl');
        return null;
    }

    private static function default_settings()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::default_settings');
        return null;
    }

    private static function get_translation()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::get_translation');
        return null;
    }

    public static function wp_mce_translation($mce_locale = '', $json_only = false)
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::wp_mce_translation');
        return null;
    }

    public static function force_uncompressed_tinymce()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::force_uncompressed_tinymce');
        return null;
    }

    public static function print_tinymce_scripts()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::print_tinymce_scripts');
    }

    public static function editor_js()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::editor_js');
        return null;
    }

    public static function wp_fullscreen_html()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::wp_fullscreen_html');
        return null;
    }

    public static function wp_link_query($args = [])
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::wp_link_query');
        return null;
    }

    public static function wp_link_dialog()
    {
        \Minn\Runtime\PlaceholderTrace::hit('_WP_Editors::wp_link_dialog');
        return null;
    }
}
