<?php
// Generated by tests/tools/stub-symbols.php from the inventory: inert placeholders for symbols plugins reference but the engine does not implement. Do not edit; regenerate.

function create_initial_taxonomies()
{
    \Minn\Runtime\PlaceholderTrace::hit('create_initial_taxonomies');
    return null;
}

function form_option($option)
{
    \Minn\Runtime\PlaceholderTrace::hit('form_option');
    return null;
}

function get_the_block_template_html()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_the_block_template_html');
    return null;
}

function set_user_setting($name, $value)
{
    \Minn\Runtime\PlaceholderTrace::hit('set_user_setting');
    return null;
}

function translate_settings_using_i18n_schema($i18n_schema, $settings, $textdomain)
{
    \Minn\Runtime\PlaceholderTrace::hit('translate_settings_using_i18n_schema');
    return null;
}

function wp($query_vars = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp');
    return null;
}

function wp_add_post_tags($post_id = 0, $tags = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_add_post_tags');
    return null;
}

function wp_admin_css($file = 'wp-admin', $force_echo = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_admin_css');
    return null;
}

function wp_admin_css_color($key, $name, $url, $colors = [], $icons = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_admin_css_color');
    return null;
}

function wp_clean_update_cache()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_clean_update_cache');
    return null;
}

function wp_editor($content, $editor_id, $settings = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_editor');
    return null;
}

function wp_enqueue_global_styles_css_custom_properties()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_enqueue_global_styles_css_custom_properties');
    return null;
}

function wp_get_post_autosave($post_id, $user_id = 0)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_get_post_autosave');
    return null;
}

function wp_heartbeat_settings($settings)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_heartbeat_settings');
    return null;
}

function wp_load_translations_early()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_load_translations_early');
    return null;
}

function wp_maybe_auto_update()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_maybe_auto_update');
    return null;
}

function wp_paused_plugins()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_paused_plugins');
    return null;
}

function wp_paused_themes()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_paused_themes');
    return null;
}

function wp_plupload_default_settings()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_plupload_default_settings');
    return null;
}

function wp_print_font_faces($fonts = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_print_font_faces');
    return null;
}

function wp_register_tinymce_scripts($scripts, $force_uncompressed = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_register_tinymce_scripts');
    return null;
}

function wp_templating_constants()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_templating_constants');
    return null;
}

function wp_timezone_choice($selected_zone, $locale = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_timezone_choice');
    return null;
}

function wp_tinymce_inline_scripts()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_tinymce_inline_scripts');
    return null;
}

function wp_update_php_annotation($before = '<p class="description">', $after = '</p>', $display = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_update_php_annotation');
    return null;
}

function wp_version_check($extra_stats = [], $force_check = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_version_check');
    return null;
}
