<?php
// Generated by tests/tools/stub-symbols.php from the inventory: inert placeholders for symbols plugins reference but the engine does not implement. Do not edit; regenerate.

function _get_list_table($class_name, $args = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('_get_list_table');
    return null;
}

function _media_states($post, $display = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('_media_states');
    return null;
}

function _unzip_file_pclzip($file, $to, $needed_dirs = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('_unzip_file_pclzip');
    return null;
}

function _wp_customize_include()
{
    \Minn\Runtime\PlaceholderTrace::hit('_wp_customize_include');
    return null;
}

function _wp_get_allowed_postdata($post_data = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('_wp_get_allowed_postdata');
    return null;
}

function _wp_get_iframed_editor_assets()
{
    \Minn\Runtime\PlaceholderTrace::hit('_wp_get_iframed_editor_assets');
    return null;
}

function _wp_post_thumbnail_html($thumbnail_id = NULL, $post = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('_wp_post_thumbnail_html');
    return null;
}

function _wp_translate_postdata($update = false, $post_data = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('_wp_translate_postdata');
    return null;
}

function add_contextual_help($screen, $help)
{
    \Minn\Runtime\PlaceholderTrace::hit('add_contextual_help');
    return null;
}

function core_update_footer($msg = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('core_update_footer');
    return null;
}

function create_initial_taxonomies()
{
    \Minn\Runtime\PlaceholderTrace::hit('create_initial_taxonomies');
    return null;
}

function edit_comment()
{
    \Minn\Runtime\PlaceholderTrace::hit('edit_comment');
    return null;
}

function edit_post($post_data = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('edit_post');
    return null;
}

function export_wp($args = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('export_wp');
    return null;
}

function find_core_auto_update()
{
    \Minn\Runtime\PlaceholderTrace::hit('find_core_auto_update');
    return null;
}

function find_core_update($version, $locale)
{
    \Minn\Runtime\PlaceholderTrace::hit('find_core_update');
    return null;
}

function find_posts_div($found_action = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('find_posts_div');
    return null;
}

function form_option($option)
{
    \Minn\Runtime\PlaceholderTrace::hit('form_option');
    return null;
}

function get_block_editor_server_block_settings()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_block_editor_server_block_settings');
    return null;
}

function get_block_editor_settings($custom_settings, $block_editor_context)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_block_editor_settings');
    return null;
}

function get_block_editor_theme_styles()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_block_editor_theme_styles');
    return null;
}

function get_comment_to_edit($id)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_comment_to_edit');
    return null;
}

function get_default_block_editor_settings()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_default_block_editor_settings');
    return null;
}

function get_default_post_to_edit($post_type = 'post', $create_in_db = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_default_post_to_edit');
    return null;
}

function get_media_items($post_id, $errors)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_media_items');
    return null;
}

function get_plugin_files($plugin)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_plugin_files');
    return null;
}

function get_preferred_from_update_core()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_preferred_from_update_core');
    return null;
}

function get_sample_permalink_html($post, $new_title = NULL, $new_slug = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_sample_permalink_html');
    return null;
}

function get_the_block_template_html()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_the_block_template_html');
    return null;
}

function get_theme_update_available($theme)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_theme_update_available');
    return null;
}

function get_user_to_edit($user_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_user_to_edit');
    return null;
}

function got_url_rewrite()
{
    \Minn\Runtime\PlaceholderTrace::hit('got_url_rewrite');
    return null;
}

function iis7_save_url_rewrite_rules()
{
    \Minn\Runtime\PlaceholderTrace::hit('iis7_save_url_rewrite_rules');
    return null;
}

function list_meta($meta)
{
    \Minn\Runtime\PlaceholderTrace::hit('list_meta');
    return null;
}

function maybe_convert_table_to_utf8mb4($table)
{
    \Minn\Runtime\PlaceholderTrace::hit('maybe_convert_table_to_utf8mb4');
    return null;
}

function media_send_to_editor($html)
{
    \Minn\Runtime\PlaceholderTrace::hit('media_send_to_editor');
    return null;
}

function media_upload_form($errors = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('media_upload_form');
    return null;
}

function media_upload_form_handler()
{
    \Minn\Runtime\PlaceholderTrace::hit('media_upload_form_handler');
    return null;
}

function media_upload_header()
{
    \Minn\Runtime\PlaceholderTrace::hit('media_upload_header');
    return null;
}

function populate_roles()
{
    \Minn\Runtime\PlaceholderTrace::hit('populate_roles');
    return null;
}

function post_tags_meta_box($post, $box)
{
    \Minn\Runtime\PlaceholderTrace::hit('post_tags_meta_box');
    return null;
}

function register_and_do_post_meta_boxes($post)
{
    \Minn\Runtime\PlaceholderTrace::hit('register_and_do_post_meta_boxes');
    return null;
}

function screen_icon()
{
    \Minn\Runtime\PlaceholderTrace::hit('screen_icon');
    return null;
}

function set_user_setting($name, $value)
{
    \Minn\Runtime\PlaceholderTrace::hit('set_user_setting');
    return null;
}

function stream_preview_image($post_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('stream_preview_image');
    return null;
}

function touch_time($edit = 1, $for_post = 1, $tab_index = 0, $multi = 0)
{
    \Minn\Runtime\PlaceholderTrace::hit('touch_time');
    return null;
}

function translate_settings_using_i18n_schema($i18n_schema, $settings, $textdomain)
{
    \Minn\Runtime\PlaceholderTrace::hit('translate_settings_using_i18n_schema');
    return null;
}

function update_core($from, $to)
{
    \Minn\Runtime\PlaceholderTrace::hit('update_core');
    return null;
}

function update_recently_edited($file)
{
    \Minn\Runtime\PlaceholderTrace::hit('update_recently_edited');
    return null;
}

function validate_file_to_edit($file, $allowed_files = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('validate_file_to_edit');
    return null;
}

function verify_file_md5($filename, $expected_md5)
{
    \Minn\Runtime\PlaceholderTrace::hit('verify_file_md5');
    return null;
}

function wp($query_vars = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp');
    return null;
}

function wp_add_post_tags($post_id = 0, $tags = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_add_post_tags');
    return null;
}

function wp_admin_css($file = 'wp-admin', $force_echo = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_admin_css');
    return null;
}

function wp_admin_css_color($key, $name, $url, $colors = [], $icons = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_admin_css_color');
    return null;
}

function wp_ajax_activate_plugin()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_ajax_activate_plugin');
    return null;
}

function wp_ajax_get_attachment()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_ajax_get_attachment');
    return null;
}

function wp_ajax_install_plugin()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_ajax_install_plugin');
    return null;
}

function wp_ajax_widgets_order()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_ajax_widgets_order');
    return null;
}

function wp_ajax_wp_link_ajax()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_ajax_wp_link_ajax');
    return null;
}

function wp_apply_border_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_border_support');
    return null;
}

function wp_apply_colors_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_colors_support');
    return null;
}

function wp_apply_custom_classname_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_custom_classname_support');
    return null;
}

function wp_apply_spacing_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_spacing_support');
    return null;
}

function wp_apply_typography_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_typography_support');
    return null;
}

function wp_category_checklist($post_id = 0, $descendants_and_self = 0, $selected_cats = false, $popular_cats = false, $walker = NULL, $checked_ontop = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_category_checklist');
    return null;
}

function wp_clean_update_cache()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_clean_update_cache');
    return null;
}

function wp_comment_trashnotice()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_comment_trashnotice');
    return null;
}

function wp_create_post_autosave($post_data)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_create_post_autosave');
    return null;
}

function wp_crop_image($src, $src_x, $src_y, $src_w, $src_h, $dst_w, $dst_h, $src_abs = false, $dst_file = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_crop_image');
    return null;
}

function wp_dashboard_cached_rss_widget($widget_id, $callback, $check_urls = [], ...$args)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_dashboard_cached_rss_widget');
    return null;
}

function wp_download_language_pack($download)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_download_language_pack');
    return null;
}

function wp_edit_attachments_query($q = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_edit_attachments_query');
    return null;
}

function wp_edit_posts_query($q = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_edit_posts_query');
    return null;
}

function wp_editor($content, $editor_id, $settings = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_editor');
    return null;
}

function wp_enqueue_global_styles_css_custom_properties()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_enqueue_global_styles_css_custom_properties');
    return null;
}

function wp_get_available_translations()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_get_available_translations');
    return null;
}

function wp_get_post_autosave($post_id, $user_id = 0)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_get_post_autosave');
    return null;
}

function wp_get_theme_file_editable_extensions($theme)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_get_theme_file_editable_extensions');
    return null;
}

function wp_heartbeat_settings($settings)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_heartbeat_settings');
    return null;
}

function wp_import_cleanup($id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_import_cleanup');
    return null;
}

function wp_import_handle_upload()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_import_handle_upload');
    return null;
}

function wp_import_upload_form($action)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_import_upload_form');
    return null;
}

function wp_install($blog_title, $user_name, $user_email, $is_public, $deprecated = '', $user_password = '', $language = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_install');
    return null;
}

function wp_load_translations_early()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_load_translations_early');
    return null;
}

function wp_maybe_auto_update()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_maybe_auto_update');
    return null;
}

function wp_nav_menu_disabled_check($nav_menu_selected_id, $display = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_nav_menu_disabled_check');
    return null;
}

function wp_nav_menu_item_post_type_meta_box($data_object, $box)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_nav_menu_item_post_type_meta_box');
    return null;
}

function wp_paused_plugins()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_paused_plugins');
    return null;
}

function wp_paused_themes()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_paused_themes');
    return null;
}

function wp_plupload_default_settings()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_plupload_default_settings');
    return null;
}

function wp_popular_terms_checklist($taxonomy, $default_term = 0, $number = 10, $display = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_popular_terms_checklist');
    return null;
}

function wp_prepare_themes_for_js($themes = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_prepare_themes_for_js');
    return null;
}

function wp_print_admin_notice_templates()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_print_admin_notice_templates');
    return null;
}

function wp_print_font_faces($fonts = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_print_font_faces');
    return null;
}

function wp_print_request_filesystem_credentials_modal()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_print_request_filesystem_credentials_modal');
    return null;
}

function wp_read_audio_metadata($file)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_read_audio_metadata');
    return null;
}

function wp_read_video_metadata($file)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_read_video_metadata');
    return null;
}

function wp_register_tinymce_scripts($scripts, $force_uncompressed = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_register_tinymce_scripts');
    return null;
}

function wp_restore_image($post_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_restore_image');
    return null;
}

function wp_save_image($post_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_save_image');
    return null;
}

function wp_should_load_block_editor_scripts_and_styles()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_should_load_block_editor_scripts_and_styles');
    return null;
}

function wp_templating_constants()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_templating_constants');
    return null;
}

function wp_terms_checklist($post_id = 0, $args = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_terms_checklist');
    return null;
}

function wp_timezone_choice($selected_zone, $locale = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_timezone_choice');
    return null;
}

function wp_tinymce_inline_scripts()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_tinymce_inline_scripts');
    return null;
}

function wp_update_image_subsizes($attachment_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_update_image_subsizes');
    return null;
}

function wp_update_php_annotation($before = '<p class="description">', $after = '</p>', $display = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_update_php_annotation');
    return null;
}

function wp_version_check($extra_stats = [], $force_check = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_version_check');
    return null;
}

function wpmu_delete_user($id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wpmu_delete_user');
    return null;
}
