<?php
// Generated by tests/tools/stub-symbols.php from the inventory: inert placeholders for symbols plugins reference but the engine does not implement. Do not edit; regenerate.

function _deep_replace($search, $subject)
{
    \Minn\Runtime\PlaceholderTrace::hit('_deep_replace');
    return null;
}

function _get_list_table($class_name, $args = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('_get_list_table');
    return null;
}

function _unzip_file_pclzip($file, $to, $needed_dirs = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('_unzip_file_pclzip');
    return null;
}

function _wp_get_iframed_editor_assets()
{
    \Minn\Runtime\PlaceholderTrace::hit('_wp_get_iframed_editor_assets');
    return null;
}

function _wp_post_thumbnail_html($thumbnail_id = NULL, $post = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('_wp_post_thumbnail_html');
    return null;
}

function add_contextual_help($screen, $help)
{
    \Minn\Runtime\PlaceholderTrace::hit('add_contextual_help');
    return null;
}

function add_magic_quotes($input_array)
{
    \Minn\Runtime\PlaceholderTrace::hit('add_magic_quotes');
    return null;
}

function addslashes_gpc($gpc)
{
    \Minn\Runtime\PlaceholderTrace::hit('addslashes_gpc');
    return null;
}

function block_template_part($part)
{
    \Minn\Runtime\PlaceholderTrace::hit('block_template_part');
    return null;
}

function cancel_comment_reply_link($link_text = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('cancel_comment_reply_link');
    return null;
}

function clean_attachment_cache($id, $clean_terms = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('clean_attachment_cache');
    return null;
}

function create_initial_taxonomies()
{
    \Minn\Runtime\PlaceholderTrace::hit('create_initial_taxonomies');
    return null;
}

function edit_comment()
{
    \Minn\Runtime\PlaceholderTrace::hit('edit_comment');
    return null;
}

function edit_post($post_data = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('edit_post');
    return null;
}

function edit_term_link($link = '', $before = '', $after = '', $term = NULL, $display = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('edit_term_link');
    return null;
}

function find_core_auto_update()
{
    \Minn\Runtime\PlaceholderTrace::hit('find_core_auto_update');
    return null;
}

function find_core_update($version, $locale)
{
    \Minn\Runtime\PlaceholderTrace::hit('find_core_update');
    return null;
}

function form_option($option)
{
    \Minn\Runtime\PlaceholderTrace::hit('form_option');
    return null;
}

function get_all_page_ids()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_all_page_ids');
    return null;
}

function get_block_editor_server_block_settings()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_block_editor_server_block_settings');
    return null;
}

function get_block_editor_settings($custom_settings, $block_editor_context)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_block_editor_settings');
    return null;
}

function get_block_editor_theme_styles()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_block_editor_theme_styles');
    return null;
}

function get_bookmarks($args = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('get_bookmarks');
    return null;
}

function get_comment_to_edit($id)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_comment_to_edit');
    return null;
}

function get_default_block_editor_settings()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_default_block_editor_settings');
    return null;
}

function get_default_post_to_edit($post_type = 'post', $create_in_db = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_default_post_to_edit');
    return null;
}

function get_dirsize($directory, $max_execution_time = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_dirsize');
    return null;
}

function get_plugin_files($plugin)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_plugin_files');
    return null;
}

function get_post_galleries($post, $html = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_post_galleries');
    return null;
}

function get_post_parent($post = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_post_parent');
    return null;
}

function get_preferred_from_update_core()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_preferred_from_update_core');
    return null;
}

function get_sample_permalink_html($post, $new_title = NULL, $new_slug = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_sample_permalink_html');
    return null;
}

function get_term_feed_link($term, $taxonomy = '', $feed = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('get_term_feed_link');
    return null;
}

function get_the_block_template_html()
{
    \Minn\Runtime\PlaceholderTrace::hit('get_the_block_template_html');
    return null;
}

function get_theme_data($theme_file)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_theme_data');
    return null;
}

function get_theme_update_available($theme)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_theme_update_available');
    return null;
}

function get_user_to_edit($user_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('get_user_to_edit');
    return null;
}

function got_url_rewrite()
{
    \Minn\Runtime\PlaceholderTrace::hit('got_url_rewrite');
    return null;
}

function has_meta($post_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('has_meta');
    return null;
}

function is_login()
{
    \Minn\Runtime\PlaceholderTrace::hit('is_login');
    return null;
}

function list_meta($meta)
{
    \Minn\Runtime\PlaceholderTrace::hit('list_meta');
    return null;
}

function media_send_to_editor($html)
{
    \Minn\Runtime\PlaceholderTrace::hit('media_send_to_editor');
    return null;
}

function media_upload_header()
{
    \Minn\Runtime\PlaceholderTrace::hit('media_upload_header');
    return null;
}

function populate_roles()
{
    \Minn\Runtime\PlaceholderTrace::hit('populate_roles');
    return null;
}

function post_tags_meta_box($post, $box)
{
    \Minn\Runtime\PlaceholderTrace::hit('post_tags_meta_box');
    return null;
}

function resolve_block_template($template_type, $template_hierarchy, $fallback_template)
{
    \Minn\Runtime\PlaceholderTrace::hit('resolve_block_template');
    return null;
}

function screen_icon()
{
    \Minn\Runtime\PlaceholderTrace::hit('screen_icon');
    return null;
}

function set_user_setting($name, $value)
{
    \Minn\Runtime\PlaceholderTrace::hit('set_user_setting');
    return null;
}

function show_message($message)
{
    \Minn\Runtime\PlaceholderTrace::hit('show_message');
    return null;
}

function stream_preview_image($post_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('stream_preview_image');
    return null;
}

function themes_api($action, $args = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('themes_api');
    return null;
}

function translate_settings_using_i18n_schema($i18n_schema, $settings, $textdomain)
{
    \Minn\Runtime\PlaceholderTrace::hit('translate_settings_using_i18n_schema');
    return null;
}

function unzip_file($file, $to)
{
    \Minn\Runtime\PlaceholderTrace::hit('unzip_file');
    return null;
}

function update_core($from, $to)
{
    \Minn\Runtime\PlaceholderTrace::hit('update_core');
    return null;
}

function walk_page_dropdown_tree(...$args)
{
    \Minn\Runtime\PlaceholderTrace::hit('walk_page_dropdown_tree');
    return null;
}

function wp($query_vars = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp');
    return null;
}

function wp_add_post_tags($post_id = 0, $tags = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_add_post_tags');
    return null;
}

function wp_admin_css($file = 'wp-admin', $force_echo = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_admin_css');
    return null;
}

function wp_admin_css_color($key, $name, $url, $colors = [], $icons = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_admin_css_color');
    return null;
}

function wp_ajax_widgets_order()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_ajax_widgets_order');
    return null;
}

function wp_apply_border_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_border_support');
    return null;
}

function wp_apply_colors_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_colors_support');
    return null;
}

function wp_apply_custom_classname_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_custom_classname_support');
    return null;
}

function wp_apply_spacing_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_spacing_support');
    return null;
}

function wp_apply_typography_support($block_type, $block_attributes)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_apply_typography_support');
    return null;
}

function wp_category_checklist($post_id = 0, $descendants_and_self = 0, $selected_cats = false, $popular_cats = false, $walker = NULL, $checked_ontop = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_category_checklist');
    return null;
}

function wp_clean_update_cache()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_clean_update_cache');
    return null;
}

function wp_comment_trashnotice()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_comment_trashnotice');
    return null;
}

function wp_create_post_autosave($post_data)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_create_post_autosave');
    return null;
}

function wp_create_tag($tag_name)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_create_tag');
    return null;
}

function wp_crop_image($src, $src_x, $src_y, $src_w, $src_h, $dst_w, $dst_h, $src_abs = false, $dst_file = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_crop_image');
    return null;
}

function wp_download_language_pack($download)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_download_language_pack');
    return null;
}

function wp_dropdown_roles($selected = '', $editable_roles = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_dropdown_roles');
    return null;
}

function wp_dropdown_users($args = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_dropdown_users');
    return null;
}

function wp_editor($content, $editor_id, $settings = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_editor');
    return null;
}

function wp_enqueue_global_styles_css_custom_properties()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_enqueue_global_styles_css_custom_properties');
    return null;
}

function wp_get_available_translations()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_get_available_translations');
    return null;
}

function wp_get_post_autosave($post_id, $user_id = 0)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_get_post_autosave');
    return null;
}

function wp_get_theme_file_editable_extensions($theme)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_get_theme_file_editable_extensions');
    return null;
}

function wp_get_update_php_url()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_get_update_php_url');
    return null;
}

function wp_heartbeat_settings($settings)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_heartbeat_settings');
    return null;
}

function wp_import_cleanup($id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_import_cleanup');
    return null;
}

function wp_import_handle_upload()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_import_handle_upload');
    return null;
}

function wp_import_upload_form($action)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_import_upload_form');
    return null;
}

function wp_load_translations_early()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_load_translations_early');
    return null;
}

function wp_maybe_auto_update()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_maybe_auto_update');
    return null;
}

function wp_paused_plugins()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_paused_plugins');
    return null;
}

function wp_paused_themes()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_paused_themes');
    return null;
}

function wp_plupload_default_settings()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_plupload_default_settings');
    return null;
}

function wp_popular_terms_checklist($taxonomy, $default_term = 0, $number = 10, $display = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_popular_terms_checklist');
    return null;
}

function wp_prepare_themes_for_js($themes = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_prepare_themes_for_js');
    return null;
}

function wp_print_admin_notice_templates()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_print_admin_notice_templates');
    return null;
}

function wp_print_font_faces($fonts = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_print_font_faces');
    return null;
}

function wp_print_request_filesystem_credentials_modal()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_print_request_filesystem_credentials_modal');
    return null;
}

function wp_read_video_metadata($file)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_read_video_metadata');
    return null;
}

function wp_restore_image($post_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_restore_image');
    return null;
}

function wp_save_image($post_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_save_image');
    return null;
}

function wp_scripts_get_suffix($type = '')
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_scripts_get_suffix');
    return null;
}

function wp_should_load_block_editor_scripts_and_styles()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_should_load_block_editor_scripts_and_styles');
    return null;
}

function wp_templating_constants()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_templating_constants');
    return null;
}

function wp_terms_checklist($post_id = 0, $args = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_terms_checklist');
    return null;
}

function wp_timezone_choice($selected_zone, $locale = NULL)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_timezone_choice');
    return null;
}

function wp_tinymce_inline_scripts()
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_tinymce_inline_scripts');
    return null;
}

function wp_update_image_subsizes($attachment_id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_update_image_subsizes');
    return null;
}

function wp_update_nav_menu_item($menu_id = 0, $menu_item_db_id = 0, $menu_item_data = [], $fire_after_hooks = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_update_nav_menu_item');
    return null;
}

function wp_update_php_annotation($before = '<p class="description">', $after = '</p>', $display = true)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_update_php_annotation');
    return null;
}

function wp_update_plugins($extra_stats = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_update_plugins');
    return null;
}

function wp_update_themes($extra_stats = [])
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_update_themes');
    return null;
}

function wp_version_check($extra_stats = [], $force_check = false)
{
    \Minn\Runtime\PlaceholderTrace::hit('wp_version_check');
    return null;
}

function wpmu_delete_user($id)
{
    \Minn\Runtime\PlaceholderTrace::hit('wpmu_delete_user');
    return null;
}
